In [ ]:
#Задание 2 переделанное

In [17]:
import pandas as pd
geo_data = {
'Центр': ['москва', 'тула', 'ярославль'],
'Северо-Запад': ['петербург', 'псков', 'мурманск'],
'Дальний Восток': ['владивосток', 'сахалин', 'хабаровск']
}

def query_region(query_text):
    for reg in geo_data.keys():
        for a in geo_data[reg]:
            if a in query_text:
                return reg
    else: return 'undefined'

keywords = pd.read_csv('C:\\ml-latest-small\\keywords.csv')
keywords['region'] = keywords['keyword'].apply(query_region)
#Для проверки
#keywords.query("keyword in ['авито москва', 'москва', 'тула', 'ярославль', 'петербург', 'псков', 'мурманск', 'владивосток', 'сахалин', 'хабаровск']")

            keyword   shows          region
127    авито москва  979292           Центр
1259         москва  153050           Центр
5858    владивосток   43038  Дальний Восток
6075      ярославль   41720           Центр
8977       мурманск   29984    Северо-Запад
9084      хабаровск   29655  Дальний Восток
11222         псков   24885    Северо-Запад
11785          тула   23898           Центр
20823     петербург   14859    Северо-Запад
21445       сахалин   14494  Дальний Восток